# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e88cdc2715a4f5892ad6d2e891fe1f972fef94f7c65930a6a0642fa78eb732fe7cd9e644d6c6ae2781d092f651a8957183e50fb877973bd411235bfe306cdf

test:
  secret_key_base: e553f4b1970498df77ffb07c410ce21a61497f54a8dea3071b1fd8aa6605d6ec3386800a1fc7ba8c1cbceacbf87f16144005500dc8d1320bad9ee3c917f7eb86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
